name: chemapi
channels:
  - conda-forge
dependencies:
  - python=3.11
  - rdkit
  - duckdb
  - fastapi
  - uvicorn
  - pandas
  - pydantic
  - chembl_webresource_client
  - pip
  - pip:
      - watchfiles
      - transformers>=4.30.0
      - torch>=1.9.0
